apiVersion: apps/v1
kind: Deployment
metadata:
  name: socks
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        args:
        - sleep infinity
        volumeMount:
        - mountPath: /var/run/docker.sock
          name: docker-socket
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket
